name: Send repository dispatch event

on:
  workflow_dispatch:

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    steps:
      - name: Fire event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/andreashofer0ca/FOSS-Request-and-Register/repository-dispatch-target-repo/dispatches \
            -d '{"event_type":"dispatch-event", "client_payload": {"message": "Hello from the trigger repository!"}}'
